### ISSUE TITLE
Is there any way of preventing the drawer from jumping on load?

### ISSUE THREAD

**Issue by cyrilzakka** [52inc/Pulley#63]
When first initializing the drawer, it seems everything is being animated from the top left of the screen into position. Is there any way of preventing this?

**Comment by brendan09** [comment]
It sounds like an issue with how you’re adding it to your view hierarchy. For example, the demo project doesn’t have that issue.

How’re you adding / presenting the controller?

**Comment by Archivus** [comment]
Doing everything from Storyboard - nothing really special about my setup. Any ideas what I should look into?

**Comment by brendan09** [comment]
Are you presenting Pulley? Or using it as a root view controller of a window? Or?

**Comment by Archivus** [comment]
Turns out changing this to false seems to have fixed the issue! 

    public func setDrawerPosition(position: PulleyPosition)
    {
        setDrawerPosition(position: position, animated: false)
    }

**Comment by brendan09** [comment]
Were you trying to set it in viewWillAppear / viewDidAppear / viewDidLoad? If so, I would definitely expect some odd visual glitches with animation enabled.

If you’re setting it in one of those locations, consider using the starting drawer position property.

**Comment by Archivus** [comment]
Yup you're definitely right - will try that instead and report back

**Comment by Archivus** [comment]
How exactly is it supposed to be used? Doesn't seem to be doing anything at all

**Comment by brendan09** [comment]
It has to be set _before_ the view is loaded. Setting it after the view has loaded has no effect. If you’re setting it within your drawer or main content VC, it’s too late as the view has already loaded.

If you’re using Interface Builder, use the initial drawer state option exposed in Interface Builder so it is set before the view loads. It accepts a string of the appropriate enum (see Pulley VC for info on that variable). The regular non-Interface Builder variable is to be used when instantiating Pulley programmatically, and should be set before doing something that causes the view to load.

**Comment by Archivus** [comment]
It worked but the jump is still there

**Comment by brendan09** [comment]
Is that the “animate from corner” issue you were having? Or something else? I’m not sure what you mean by a “jump”?

**Comment by Archivus** [comment]
Yup still the animation from corner issue, my bad. You really don't have to worry about it for now - my temporary solution seems to have worked with no repercussions. Thank you for your time btw

**Comment by brendan09** [comment]
Ok- glad it worked for you. A lot of people seem to be interested in presenting Pulley as a VC (instead of as a root view controller), and it’s never really been tested / debugged for that use case. I’ll add that to my list of things to work on, so hopefully some of these issues can be prevented. Thanks for your patience! Glad you found a workaround.

**Comment by PomepuyN** [comment]
I second this issue. 
I am currently using a `PulleyViewController` in an `UITabBarController` and when you load a tab for the first time, the drawer is jumping.
The only way to solve it for now is to import the lib manually and change the first `setDrawerPosition`call to avoid the animation.
A quick and easy fix would be to declare this method `open` so we can override it (and avoid having to clone the entire library).
Another one could be to allow the drawer not to animate the first `setDrawerPosition`call.

**Comment by azurechen** [comment]
I have a totally same issue. But my PulleyController is the destination of a segue. the whole view will jump at enter this PulleyController.

and I fixed this problem with the same solution.

```
public func setDrawerPosition(position: PulleyPosition)
{
    setDrawerPosition(position: position, animated: false)
}
```

Maybe next version can solve this problem? Or just open `setDrawerPosition` for overriding should be great too.

**Comment by brendan09** [comment]
@PomepuyN @azurechen Thanks for the info. I just pushed a proposed solution to master. Can you guys try the current 'master' branch (download or point your Podfile to it) and see if that works for you?

NOTE: The change is that I added an optional parameter to `setDrawerPosition` that allows you to specify whether or not to animate the change.

You can convert your current call to `setDrawerPosition` from this:

     pulley.setDrawerPosition(position: .collapsed)

to:

     pulley.setDrawerPosition(position: .collapsed, isAnimated: false)

I think it's more appropriate to yield the animation option to the app as an option, rather than add work-arounds for situations where people may not want it animated.

Let me know if it works for you. If it does, I'll push it out over CocoaPods.

**Comment by PomepuyN** [comment]
Hi,
Thanks for the quick answer but I am not sure how to use it (and I think I did not explain really well the issue).

## Bug explanation

I do not call `setDrawerPosition` at all, it's the `initialDrawerPositionFromIB` that is broken when used in another tab.

Here is my StoryBoard:
![StoryBoard](https://i.imgur.com/QYE3sr7.png)

As you can see, I use `Pulley` in the second tab.
When I open it, even if the `initialDrawerPositionFromIB` is set to "collapsed", the drawer is animated from the top.

Here is the stack leading to `setDrawerPosition(position: .collapsed, isAnimated: true)`

```
PulleyViewController.viewDidLoad()
 ↘️ PulleyViewController.primaryContentViewController.didset
    ↘️ PulleyViewController.setNeedsSupportedDrawerPositionsUpdate()
       ↘️ PulleyViewController.supportedPositions.didset
          ↘️ PulleyViewController.setDrawerPosition(position:isAnimated:) //animated is true
```

You can simply debug it in the attached sample project by adding a breakpoint in `PulleyViewController.setDrawerPosition()` at the first line and see that the first call is animated.

[PulleyTest.zip](https://github.com/52inc/Pulley/files/1436748/PulleyTest.zip)

## Proposed solution

My proposed solution was to allow us the override `setDrawerPosition`.
The reason is that you may not want to manage this special case (in which Pulley is embed a another tab) as it may have side effects on the "natural" use case.

In this case, I would use a class extending `PulleyViewController` and forcing animation to false if the call is the first one (even if I agree, it would just be a workaround).

The ideal solution would be to make it work in my case though.

I hope that I have made it clearer and sorry if not (I am relatively new to iOS development).

**Comment by azhang66** [comment]
Unfortunately, this bug is still present, [**even in the demo app**](https://streamable.com/43qmg). The effect in the demo app is somewhat obscured by the iOS app loading animation, but you can clearly see that Pulley animates the drawer jumping from the top left of the screen.

Looking at the [PullyViewController.swift](https://github.com/52inc/Pulley/blob/c1899d110eb4ecf33c8fc1776f1b06da0db062ca/PulleyLib/PulleyViewController.swift#L617), it looks like `setDrawerPosition()` is called, with `animated: false`. However, it's evident that the animation occurs anyway. My suspicion is that the "jumping" animation that we're seeing from the top left corner is not the animation caused by `setDrawerPosition()`.

@brendan09 thoughts?

**Comment by brendan09** [comment]
I’ll take a closer look and see what I can find.

I won’t be marking setDrawerPosition as open, however, as it would require making far too many internal variables and functions public in order for people to write their own implementation of the function.

**Comment by azhang66** [comment]
That's fine (I probably couldn't figure out how to reimplement it anyways). I think the main issue here is getting rid of the corner jumps (which shouldn't be there even by default).

**Comment by brendan09** [comment]
Ok, everyone. I think I have a fix for this. Sorry about the delay / misunderstanding the issue.

@azhang66 If you're still near some code, do you mind giving the current code on Master a try? The fix worked for the sample project. I'm about to test it on the sample from @PomepuyN to see it it fixes that use case as well.

**Comment by brendan09** [comment]
Okay, the fix seems to work for the sample project from @PomepuyN as well.

I'm going to go ahead and push this out over CocoaPods after a few more minutes of testing.

**Comment by brendan09** [comment]
Okay, after some additional testing I've gone ahead and pushed this fix out to CocoaPods. It's version '2.2.9'. Assuming you haven't pinned your Pulley version, you can get the update by doing `pod update Pulley`. You made need to run `pod repo update` first.

Since this seems to be important to a lot of people, I'm gonna tag the people interested in this thread below so they see the notification.

@cyrilzakka @PomepuyN @azurechen @azhang66 @Vadim4016 @pablomarcos

If anyone has any issues, please let me know. I'll try to get them taken care of ASAP. Once a few people have reported back with success, then I'll close the issue. Thanks, everyone.

**Comment by azhang66** [comment]
Fixed for me. Thanks!

**Comment by PomepuyN** [comment]
The new version also fixed the issue for me

**Comment by cyrilzakka** [comment]
@brendan09 thanks for your work mate!

**Comment by brendan09** [comment]
Fantastic! I'm going to go ahead and close this issue then. Thanks for the help in tracking this one down, everyone!
