### ISSUE TITLE
`UIButton` highlighting is delayed

### ISSUE THREAD

**Issue by Dschee** [52inc/Pulley#75]
When I add a UIButton in my drawer view controller then all UIButton's highlightings are delayed. I want my `UIScrollView` objects which hold buttons **not** to be delayed, but I can't find an option to configure this with Pulley.

**Comment by cyrilzakka** [comment]
Set button type to custom

**Comment by Dschee** [comment]
But then I don‘t habe the default button title highlighting by the system, right? That wouldn‘t be a real solution for me as I want to keep the default highlighting behavior ...

**Comment by grifas** [comment]
Same issue here

**Comment by brendan09** [comment]
@grifas This was addressed in a version bump a year or so ago. You can change the delaysContentTouches property on Pulley.

**Comment by grifas** [comment]
I tried to turn it to false but that doesn't fix the issue :/
